'''Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.'''
#Ans)Yes, there is a difference in the data type of the list_ variable and the array_list variable. The list_ variable is a Python list, while the array_list variable is a NumPy array
import numpy as np

In [3]:
import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_ variable:", type(list_))
print("Data type of array_list variable:", type(array_list))

Data type of list_ variable: <class 'list'>
Data type of array_list variable: <class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [4]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of elements in list_ variable:")
for item in list_:
    print(type(item))

print("\nData type of elements in array_list variable:")
for item in array_list:
    print(type(item))


Data type of elements in list_ variable:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of elements in array_list variable:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

Ans)Yes, there will be a difference in the data type of the elements present in both variables, list_ and array_list, after specifying the dtype=int parameter when creating the NumPy array array_list. This parameter explicitly sets the data type of the elements in the array to integer.

In [5]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

print("Data type of elements in list_ variable:")
for item in list_:
    print(type(item))

print("\nData type of elements in array_list variable:")
for item in array_list:
    print(type(item))


Data type of elements in list_ variable:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of elements in array_list variable:
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [6]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)


Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [9]:
# (i) Shape of the array
shape = num_array.shape

# (ii) Size of the array
size = num_array.size

print("Shape of num_array:", shape)
print("Size of num_array:", size)

Shape of num_array: (2, 3)
Size of num_array: 6



Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [10]:
#You can create a NumPy array of a 3x3 matrix containing zeros only using the np.zeros() function. Here's the code:


import numpy as np

# Creating a 3x3 array with zeros
zeros_array = np.zeros((3, 3))

print("Zeros Array:")
print(zeros_array)

Zeros Array:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [11]:
import numpy as np

# Creating an identity matrix of shape (5, 5)
identity_matrix = np.eye(5)

print("Identity Matrix:")
print(identity_matrix)


Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
